name: Update Spotify Now Playing

on:
  # This runs the job on a schedule (every 5 minutes)
  schedule:
    - cron: '*/5 * * * *'
  
  # This allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  spotify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Novatorem/spotify-readme@main
        with:
          spotify_client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          spotify_client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          spotify_refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
