name: Update Spotify Now Playing

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  spotify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Novatorem/spotify-readme@master # <--- THIS IS THE LINE WE FIXED
        with:
          spotify_client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          spotify_client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          spotify_refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
